# Generated by Django 5.1.2 on 2024-11-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='events',
            new_name='created_events',
        ),
    ]
